/**
 * Product feature ontology — grouping axis for API suggest (not provider domains).
 */

export const FEATURES = [
  {
    id: "address-autocomplete",
    label: "Address autocomplete",
    parentId: "address-geocoding",
    why: "Help users pick valid addresses quickly as they type",
    where: "Checkout delivery field, signup address, search bar with typeahead",
    keywords: [
      "autocomplete", "typeahead", "suggest", "address input", "address field", "geosuggest",
    ],
    capabilityTags: ["address-autocomplete", "geocode"],
    categories: ["Maps & location"],
    providers: ["2gis", "yandex"],
  },
  {
    id: "forward-geocode",
    label: "Address → coordinates",
    parentId: "address-geocoding",
    why: "Turn street addresses into map coordinates for routing and pins",
    where: "After address submit, order confirmation, geocoding batch jobs",
    keywords: [
      "geocode", "geocoder", "geocoordinator", "coordinates", "lat", "lng", "forward geocode",
      "address to coordinates",
    ],
    capabilityTags: ["geocode", "forward-geocode"],
    categories: ["Maps & location"],
    providers: ["2gis", "yandex"],
  },
  {
    id: "reverse-geocode",
    label: "Coordinates → address",
    parentId: "address-geocoding",
    why: "Show human-readable addresses from map pins or GPS points",
    where: "Map pin drop, courier GPS trace, location share screen",
    keywords: ["reverse geocode", "reverse geocoding", "pin drop", "map pin", "gps to address"],
    capabilityTags: ["reverse-geocode", "geocode"],
    categories: ["Maps & location"],
    providers: ["2gis", "yandex"],
  },
  {
    id: "address-geocoding",
    label: "Address lookup",
    parentId: null,
    why: "Convert between addresses and map coordinates",
    where: "Address forms, map screens, delivery location capture",
    keywords: [
      "address", "geocoding", "geolocation", "location", "maps address", "coordinates",
    ],
    capabilityTags: ["geocode", "reverse-geocode", "forward-geocode", "address-autocomplete"],
    categories: ["Maps & location"],
    providers: ["2gis", "yandex"],
  },
  {
    id: "poi-search",
    label: "Places & POI search",
    parentId: null,
    why: "Find businesses, landmarks and organizations on a map",
    where: "Store locator, nearby search, restaurant browse map",
    keywords: ["poi", "places", "organization", "nearby", "catalog", "2gis places", "store locator"],
    capabilityTags: ["poi-search", "places"],
    categories: ["Maps & location"],
    providers: ["2gis", "yandex"],
  },
  {
    id: "delivery-eta",
    label: "Delivery time estimates",
    parentId: "logistics-routing",
    why: "Show how long delivery or travel will take between stops",
    where: "Checkout ETA, courier dispatch board, order tracking",
    keywords: [
      "eta", "delivery time", "courier", "distance matrix", "travel time", "duration", "arrival time",
    ],
    capabilityTags: ["distance-matrix", "delivery-eta", "routing"],
    categories: ["Maps & location", "Travel & mobility", "Logistics & delivery"],
    providers: ["2gis", "yandex"],
  },
  {
    id: "route-planning",
    label: "Route planning",
    parentId: "logistics-routing",
    why: "Draw drive, walk or bike routes between points",
    where: "Courier navigation, driver app, trip planner map",
    keywords: ["routing", "route", "navigation", "directions", "drive", "walk", "bike"],
    capabilityTags: ["routing", "route-planning"],
    categories: ["Maps & location", "Travel & mobility"],
    providers: ["2gis", "yandex", "indriver"],
  },
  {
    id: "delivery-zones",
    label: "Delivery coverage zones",
    parentId: "logistics-routing",
    why: "Define where you can deliver or serve customers on a map",
    where: "Delivery zone settings, store coverage map, fee zone rules",
    keywords: ["isochrone", "coverage", "delivery zone", "service area", "reachable"],
    capabilityTags: ["isochrone", "delivery-zones"],
    categories: ["Maps & location"],
    providers: ["2gis", "yandex"],
  },
  {
    id: "logistics-routing",
    label: "Logistics & routing",
    parentId: null,
    why: "Plan routes, ETAs and delivery coverage for couriers and fleets",
    where: "Dispatch, fleet ops, delivery fee and ETA flows",
    keywords: ["logistics", "fleet", "courier routing", "last mile", "dispatch"],
    capabilityTags: ["routing", "distance-matrix", "delivery-eta", "isochrone"],
    categories: ["Maps & location", "Logistics & delivery", "Travel & mobility"],
    providers: ["2gis", "yandex"],
  },
  {
    id: "checkout-payment",
    label: "Checkout payments",
    parentId: null,
    why: "Charge customers when they confirm an order or subscription",
    where: "Checkout confirm step, pay button, invoice settlement",
    keywords: [
      "pay", "payment", "payments", "checkout", "kaspi", "freedompay", "wooppay", "paybox", "qiwi",
      "card", "acquiring", "merchant", "pos", "qr pay",
    ],
    capabilityTags: ["checkout-payment", "qr-payment", "wallet-payment"],
    categories: ["Payments", "Banking & finance"],
    providers: ["kaspi", "freedompay", "wooppay", "paybox", "qiwi", "halyk", "npck"],
    negativeKeywords: ["exchange rate", "statistics", "population"],
  },
  {
    id: "wallet-payout",
    label: "Wallet & payouts",
    parentId: null,
    why: "Send money to users, sellers or bank accounts",
    where: "Seller payouts, refunds, B2C transfers, wallet top-up",
    keywords: ["payout", "transfer", "wallet", "withdraw", "imps", "disbursement"],
    capabilityTags: ["wallet-payout", "bank-transfer"],
    categories: ["Payments", "Banking & finance"],
    providers: ["npck", "kaspi", "halyk"],
  },
  {
    id: "fx-rates",
    label: "Exchange rates & FX",
    parentId: null,
    why: "Show official or market FX rates in dashboards and converters",
    where: "Currency converter, finance dashboard, pricing screens",
    keywords: ["fx", "exchange rate", "currency", "nbk rate", "forex", "convert currency"],
    capabilityTags: ["fx-rates", "exchange-rates"],
    categories: ["Banking & finance", "Finance", "Financial Markets", "Prices"],
    providers: ["nbk", "nationalbank"],
    negativeKeywords: ["checkout", "pay", "horse", "student app"],
  },
  {
    id: "bank-accounts",
    label: "Bank account data",
    parentId: null,
    why: "Read balances and transactions after user consent",
    where: "Open banking onboarding, account aggregation, PFM apps",
    keywords: ["open banking", "account balance", "transactions", "bank account", "npck", "consent"],
    capabilityTags: ["bank-accounts", "open-banking"],
    categories: ["Banking & finance", "Payments"],
    providers: ["npck", "halyk", "forte"],
  },
  {
    id: "user-auth",
    label: "Sign-in & identity",
    parentId: null,
    why: "Let users register and log in securely",
    where: "Registration screen, login modal, SSO redirect",
    keywords: ["auth", "login", "signup", "oauth", "identity", "yandex id", "finid", "kyc", "verify"],
    capabilityTags: ["user-auth", "oauth", "identity"],
    categories: ["Auth & identity", "Government services"],
    providers: ["yandex", "sigex", "egov", "npck"],
  },
  {
    id: "esignature",
    label: "E-signature & EDS",
    parentId: null,
    why: "Sign contracts and documents with legal digital signatures",
    where: "Contract signing flow, HR onboarding, gov form submit",
    keywords: ["signature", "eds", "sigex", "e-sign", "digital signature", "document sign"],
    capabilityTags: ["esignature", "eds"],
    categories: ["Auth & identity", "Government services"],
    providers: ["sigex", "egov"],
  },
  {
    id: "sms-otp",
    label: "SMS & OTP",
    parentId: null,
    why: "Send one-time codes and transactional SMS",
    where: "Login OTP step, order updates, phone verification",
    keywords: ["sms", "otp", "text message", "verification code", "beeline", "kcell", "tele2"],
    capabilityTags: ["sms-otp", "sms"],
    categories: ["Communications"],
    providers: ["beeline", "kcell", "tele2", "altel"],
  },
  {
    id: "food-delivery-partner",
    label: "Food delivery integration",
    parentId: null,
    why: "Hand off orders to a delivery or restaurant network",
    where: "Post-checkout handoff, restaurant partner portal",
    keywords: ["glovo", "wolt", "food delivery", "restaurant delivery", "order food"],
    capabilityTags: ["food-delivery", "delivery-partner"],
    categories: ["Food & delivery", "E-commerce"],
    providers: ["glovo", "wolt", "chocofamily"],
  },
  {
    id: "parcel-shipping",
    label: "Parcel shipping",
    parentId: null,
    why: "Ship parcels and track packages nationally",
    where: "Shipping label creation, tracking page, returns flow",
    keywords: ["parcel", "shipping", "cdek", "kazpost", "track package", "logistics"],
    capabilityTags: ["parcel-shipping", "tracking"],
    categories: ["Logistics & delivery", "E-commerce"],
    providers: ["cdek", "kazpost"],
  },
  {
    id: "marketplace-sync",
    label: "Marketplace & catalog sync",
    parentId: null,
    why: "Sync products and orders with marketplaces",
    where: "Seller dashboard, inventory sync jobs, order webhooks",
    keywords: ["marketplace", "wildberries", "ozon", "seller", "sku", "inventory", "ecommerce"],
    capabilityTags: ["marketplace-sync", "catalog-sync"],
    categories: ["E-commerce"],
    providers: ["wildberries", "ozon", "yandex market"],
  },
  {
    id: "travel-booking",
    label: "Travel & tickets",
    parentId: null,
    why: "Search and book flights, trains or buses",
    where: "Travel search results, booking checkout, ticket wallet",
    keywords: ["flight", "train", "ticket", "aviata", "air astana", "railways", "ktz", "travel book"],
    capabilityTags: ["travel-booking", "flights", "trains"],
    categories: ["Travel & mobility", "Transport"],
    providers: ["aviata", "air astana", "flyarystan", "scat", "ktz"],
  },
  {
    id: "weather-forecast",
    label: "Weather forecasts",
    parentId: null,
    why: "Show weather for planning screens and logistics",
    where: "Home dashboard, delivery delay alerts, agriculture views",
    keywords: ["weather", "forecast", "kazhydromet", "temperature", "climate", "rain"],
    capabilityTags: ["weather-forecast"],
    categories: ["Environment & climate", "Environment"],
    providers: ["kazhydromet"],
  },
  {
    id: "gov-open-data",
    label: "Government open data",
    parentId: null,
    why: "Use verified public statistics and registry datasets",
    where: "Analytics dashboards, research tools, civic apps",
    keywords: [
      "open data", "statistics", "egov", "population", "demography", "kato", "dataset", "stat.gov",
      "government data",
    ],
    capabilityTags: ["gov-open-data", "statistics"],
    categories: [
      "Government data",
      "Demography",
      "Population & society",
      "Statistical Indicators",
      "Public Administration",
    ],
    providers: ["egov", "stat.gov", "data.egov"],
    negativeKeywords: ["checkout", "geocode", "payment", "horse riding", "student app"],
  },
  {
    id: "ai-assistant",
    label: "AI & chat features",
    parentId: null,
    why: "Add LLM assistants, search ranking or generated content",
    where: "In-app chat, help bot, content generation panel",
    keywords: ["ai", "llm", "gpt", "yandexgpt", "chatbot", "assistant", "nlp"],
    capabilityTags: ["ai-assistant", "llm"],
    categories: ["AI"],
    providers: ["yandex"],
  },
  {
    id: "analytics-tracking",
    label: "Analytics & measurement",
    parentId: null,
    why: "Measure product usage and marketing performance",
    where: "App install, page views, conversion funnels",
    keywords: ["analytics", "metrica", "appmetrica", "tracking", "measurement"],
    capabilityTags: ["analytics-tracking"],
    categories: ["Communications"],
    providers: ["yandex"],
  },
  {
    id: "ads-campaigns",
    label: "Ads & campaigns",
    parentId: null,
    why: "Run and manage advertising campaigns",
    where: "Marketing dashboard, campaign creation, ad spend reports",
    keywords: ["ads", "advertising", "yandex direct", "campaign", "marketing"],
    capabilityTags: ["ads-campaigns"],
    categories: ["Communications"],
    providers: ["yandex"],
  },
  {
    id: "tax-invoicing",
    label: "Tax & e-invoicing",
    parentId: null,
    why: "Issue electronic invoices and sync with tax systems",
    where: "Invoice generation, ERP sync, VAT reporting",
    keywords: ["tax", "esf", "e-invoice", "vat", "kgd", "invoice"],
    capabilityTags: ["tax-invoicing", "e-invoice"],
    categories: ["E-invoicing & tax"],
    providers: ["kgd", "esf"],
  },
  {
    id: "cloud-hosting",
    label: "Cloud & hosting",
    parentId: null,
    why: "Run backend infra, storage and managed services",
    where: "DevOps setup, file storage, compute provisioning",
    keywords: ["cloud", "hosting", "storage", "yandex cloud", "ps.kz", "server"],
    capabilityTags: ["cloud-hosting"],
    categories: ["Cloud & infrastructure"],
    providers: ["yandex", "ps"],
  },
];

/** Whole-product shortcuts — boost features when prompt matches a known app type. */
export const PRODUCT_RECIPES = [
  {
    id: "food-delivery",
    match: ["food delivery", "delivery app", "restaurant app", "order food", "glovo", "wolt", "courier app"],
    features: ["address-autocomplete", "checkout-payment", "delivery-eta", "route-planning"],
  },
  {
    id: "fintech-wallet",
    match: ["fintech", "wallet app", "digital wallet", "pfm", "personal finance"],
    features: ["checkout-payment", "fx-rates", "bank-accounts", "user-auth"],
  },
  {
    id: "marketplace",
    match: ["marketplace", "multi vendor", "seller platform", "wildberries", "ozon seller"],
    features: ["marketplace-sync", "checkout-payment", "address-autocomplete", "parcel-shipping"],
  },
  {
    id: "travel-planner",
    match: ["travel app", "trip planner", "book flights", "train tickets"],
    features: ["travel-booking", "address-autocomplete", "route-planning"],
  },
  {
    id: "gov-dashboard",
    match: ["gov dashboard", "open data portal", "statistics dashboard", "civic data"],
    features: ["gov-open-data", "weather-forecast"],
  },
];

const featureById = new Map(FEATURES.map((f) => [f.id, f]));

export function getFeature(id) {
  return featureById.get(id) || null;
}

export function getParentFeature(feature) {
  if (!feature?.parentId) return null;
  return getFeature(feature.parentId);
}

export function featureSearchText(feature) {
  return [
    feature.label,
    feature.why,
    feature.where,
    ...(feature.keywords || []),
    ...(feature.capabilityTags || []),
  ]
    .filter(Boolean)
    .join(" ");
}
