/**
 * Second-wave feature catalog — domain-specific atoms for proper per-category coverage.
 */

/** @param {Partial<import('./features.js').Feature> & { id: string, label: string }} f */
function feat(f) {
  return {
    parentId: null,
    why: `Support ${f.label.toLowerCase()} in Kazakhstan product flows`,
    where: "Dashboards, research tools, or backend data pipelines",
    keywords: [f.label.toLowerCase(), ...(f.keywords || [])],
    capabilityTags: f.capabilityTags || ["gov-open-data", "statistics"],
    categories: f.categories || ["Government data"],
    providers: f.providers || ["bureau", "egov"],
    ...f,
  };
}

function gov(id, label, extra = {}) {
  return feat({
    id,
    label,
    parentId: extra.parentId || "gov-open-data",
    categories: extra.categories || ["Government data"],
    keywords: extra.keywords || [label.toLowerCase()],
    capabilityTags: extra.capabilityTags || ["gov-open-data", "statistics"],
  });
}

/** @type {import('./features.js').Feature[]} */
export const EXTENDED_FEATURES_WAVE2 = [
  // Demography & population depth
  gov("mortality-stats", "Mortality & death statistics", { categories: ["Demography", "Health", "Population & society"], keywords: ["mortality", "death rate", "deaths"], parentId: "health-stats" }),
  gov("fertility-stats", "Fertility & birth statistics", { categories: ["Demography", "Population & society"], keywords: ["fertility", "birth rate", "births"], parentId: "population-stats" }),
  gov("life-expectancy", "Life expectancy indicators", { categories: ["Demography", "Health"], keywords: ["life expectancy", "longevity"] }),
  gov("urbanization-stats", "Urbanization statistics", { categories: ["Demography", "Population & society"], keywords: ["urbanization", "urban population"] }),
  gov("rural-population", "Rural population data", { categories: ["Demography", "Population & society"], keywords: ["rural population", "village stats"] }),
  gov("urban-population", "Urban population data", { categories: ["Demography", "Population & society"], keywords: ["urban population", "city population"] }),
  gov("internal-migration", "Internal migration flows", { categories: ["Demography", "Population & society"], keywords: ["internal migration", "domestic migration"], parentId: "migration-stats" }),
  gov("external-migration", "International migration", { categories: ["Demography", "Population & society"], keywords: ["international migration", "emigration immigration"], parentId: "migration-stats" }),
  gov("household-size", "Household size statistics", { categories: ["Households", "Population & society"], keywords: ["household size", "average household"], parentId: "household-stats" }),
  gov("family-structure", "Family structure data", { categories: ["Households", "Population & society"], keywords: ["family structure", "family composition"], parentId: "household-stats" }),
  gov("dependency-ratio", "Age dependency ratios", { categories: ["Demography", "Population & society"], keywords: ["dependency ratio", "age dependency"] }),
  gov("working-age-population", "Working-age population", { categories: ["Demography", "Labour Markets"], keywords: ["working age", "labour force age"] }),
  gov("youth-population", "Youth population indicators", { categories: ["Demography", "Education"], keywords: ["youth population", "children stats"] }),
  gov("aging-population", "Aging population indicators", { categories: ["Demography", "Health"], keywords: ["aging population", "elderly population"] }),
  gov("literacy-rate", "Literacy & education rates", { categories: ["Education", "Population & society"], keywords: ["literacy rate", "literacy stat"], parentId: "education-stats" }),

  // Health depth
  gov("vaccination-stats", "Vaccination coverage", { categories: ["Health", "Healthcare"], keywords: ["vaccination", "immunization rate"], parentId: "health-stats" }),
  gov("disease-incidence", "Disease incidence rates", { categories: ["Health", "Healthcare"], keywords: ["disease incidence", "morbidity"], parentId: "disease-surveillance" }),
  gov("tuberculosis-stats", "Tuberculosis statistics", { categories: ["Health", "Healthcare"], keywords: ["tuberculosis", "tb stats"], parentId: "health-stats" }),
  gov("cancer-stats", "Cancer registry statistics", { categories: ["Health", "Healthcare"], keywords: ["cancer stat", "oncology registry"], parentId: "health-stats" }),
  gov("mental-health-stats", "Mental health indicators", { categories: ["Health", "Healthcare"], keywords: ["mental health stat", "psychiatric"], parentId: "health-stats" }),
  gov("bed-occupancy", "Hospital bed occupancy", { categories: ["Health", "Healthcare"], keywords: ["bed occupancy", "hospital beds"], parentId: "hospital-capacity" }),
  gov("physician-density", "Physician & nurse density", { categories: ["Health", "Healthcare"], keywords: ["physician density", "doctor per capita"], parentId: "health-stats" }),
  gov("pharmacy-stats", "Pharmacy & drug statistics", { categories: ["Health", "Healthcare"], keywords: ["pharmacy stat", "drug consumption"], parentId: "health-stats" }),
  gov("blood-donation-stats", "Blood donation statistics", { categories: ["Health", "Healthcare"], keywords: ["blood donation", "donor stats"], parentId: "health-stats" }),

  // Education depth
  gov("teacher-stats", "Teacher & staff statistics", { categories: ["Education"], keywords: ["teacher stat", "teaching staff"], parentId: "education-stats" }),
  gov("school-capacity", "School capacity & facilities", { categories: ["Education"], keywords: ["school capacity", "classroom stat"], parentId: "education-stats" }),
  gov("graduation-rates", "Graduation & completion rates", { categories: ["Education"], keywords: ["graduation rate", "completion rate"], parentId: "education-stats" }),
  gov("vocational-training", "Vocational training stats", { categories: ["Education", "Labour Markets"], keywords: ["vocational training", "tvet stat"], parentId: "education-stats" }),
  gov("research-output", "Research & R&D statistics", { categories: ["Education", "Economic Sectors"], keywords: ["research output", "r&d stat"], parentId: "education-stats" }),

  // Labour & income
  gov("unemployment-rate", "Unemployment statistics", { categories: ["Labour Markets", "Work & income"], keywords: ["unemployment rate", "jobless"], parentId: "labour-stats" }),
  gov("wage-statistics", "Wage & salary statistics", { categories: ["Labour Markets", "Work & income"], keywords: ["wage stat", "salary stat", "earnings"], parentId: "labour-stats" }),
  gov("employment-by-sector", "Employment by sector", { categories: ["Labour Markets", "Economic Sectors"], keywords: ["employment by sector", "jobs by industry"], parentId: "labour-stats" }),
  gov("job-vacancies", "Job vacancy statistics", { categories: ["Labour Markets"], keywords: ["job vacancy", "vacancy rate"], parentId: "labour-stats" }),
  gov("informal-employment", "Informal employment data", { categories: ["Labour Markets", "Work & income"], keywords: ["informal employment", "informal sector"], parentId: "labour-stats" }),
  gov("poverty-indicators", "Poverty & inequality indicators", { categories: ["Households", "Public Welfare"], keywords: ["poverty rate", "gini", "inequality"], parentId: "household-stats" }),
  gov("consumption-expenditure", "Consumption expenditure", { categories: ["Households", "Prices"], keywords: ["consumption expenditure", "consumer spending"], parentId: "household-stats" }),

  // Housing & property
  gov("construction-permits", "Construction permit statistics", { categories: ["Housing & property", "Property"], keywords: ["construction permit", "building permit"], parentId: "housing-stats" }),
  gov("housing-starts", "Housing construction starts", { categories: ["Housing & property", "Property"], keywords: ["housing starts", "new construction"], parentId: "housing-stats" }),
  gov("rent-index", "Rental price indices", { categories: ["Housing & property", "Prices"], keywords: ["rent index", "rental price"], parentId: "housing-stats" }),
  gov("mortgage-stats", "Mortgage & housing finance", { categories: ["Housing & property", "Banking & finance"], keywords: ["mortgage stat", "housing loan"], parentId: "housing-stats" }),
  gov("cadastral-data", "Cadastral & land registry", { categories: ["Housing & property", "Property"], keywords: ["cadastral", "land registry", "cadastre"], parentId: "housing-stats" }),

  // Economy, prices, finance
  gov("gdp-components", "GDP components & growth", { categories: ["National Accounts", "Economy & business"], keywords: ["gdp growth", "gdp components"], parentId: "national-accounts" }),
  gov("inflation-cpi", "CPI inflation statistics", { categories: ["Prices", "National Accounts"], keywords: ["cpi inflation", "consumer inflation"], parentId: "price-indices" }),
  gov("producer-prices", "Producer price indices", { categories: ["Prices", "National Accounts"], keywords: ["ppi", "producer price"], parentId: "price-indices" }),
  gov("food-price-index", "Food price monitoring", { categories: ["Prices", "Food & delivery"], keywords: ["food price index", "food inflation"], parentId: "price-indices" }),
  gov("fuel-price-index", "Fuel & energy prices", { categories: ["Prices", "Commodities & metals"], keywords: ["fuel price index", "energy price"], parentId: "price-indices" }),
  gov("exchange-rate-policy", "Exchange rate policy rates", { categories: ["Financial Markets", "Finance"], keywords: ["policy rate", "base rate", "refinancing rate"], parentId: "interest-rates" }),
  gov("money-supply", "Money supply indicators", { categories: ["Financial Markets", "National Accounts"], keywords: ["money supply", "m2 m3"], parentId: "national-accounts" }),
  gov("credit-volume", "Bank credit volume", { categories: ["Financial Markets", "Banking & finance"], keywords: ["credit volume", "bank lending"], parentId: "bank-accounts" }),
  gov("deposit-stats", "Bank deposit statistics", { categories: ["Financial Markets", "Banking & finance"], keywords: ["deposit stat", "bank deposits"], parentId: "bank-accounts" }),
  gov("public-debt", "Public debt statistics", { categories: ["National Accounts", "Financial Markets"], keywords: ["public debt", "government debt"], parentId: "national-accounts" }),
  gov("budget-execution", "Budget execution data", { categories: ["Public Administration", "National Accounts"], keywords: ["budget execution", "fiscal stat"], parentId: "national-accounts" }),
  gov("tax-revenue", "Tax revenue statistics", { categories: ["Public Administration", "E-invoicing & tax"], keywords: ["tax revenue", "fiscal revenue"], parentId: "tax-invoicing" }),
  gov("insurance-sector", "Insurance sector statistics", { categories: ["Financial Markets", "Banking & finance"], keywords: ["insurance stat", "premium volume"], parentId: "national-accounts" }),
  gov("stock-market-stats", "Stock market indicators", { categories: ["Financial Markets"], keywords: ["stock market", "kase index", "equity market"] }),
  gov("bond-market-stats", "Bond market statistics", { categories: ["Financial Markets"], keywords: ["bond market", "yield curve stat"], parentId: "interest-rates" }),

  // Industry, trade, agriculture
  gov("agricultural-output", "Agricultural output statistics", { categories: ["Economic Sectors", "Economy & business"], keywords: ["agricultural output", "farm production"], parentId: "industry-sectors" }),
  gov("crop-yield", "Crop yield statistics", { categories: ["Economic Sectors", "Environment"], keywords: ["crop yield", "harvest stat"], parentId: "agricultural-output" }),
  gov("livestock-stats", "Livestock statistics", { categories: ["Economic Sectors"], keywords: ["livestock stat", "cattle sheep"], parentId: "agricultural-output" }),
  gov("industrial-production", "Industrial production index", { categories: ["Economic Sectors", "Economy & business"], keywords: ["industrial production", "manufacturing index"], parentId: "industry-sectors" }),
  gov("mining-output", "Mining & extraction output", { categories: ["Economic Sectors", "Commodities & metals"], keywords: ["mining output", "extraction stat"], parentId: "industry-sectors" }),
  gov("construction-output", "Construction sector output", { categories: ["Economic Sectors", "Housing & property"], keywords: ["construction output", "building sector"], parentId: "industry-sectors" }),
  gov("retail-turnover", "Retail trade turnover", { categories: ["Economy & business", "E-commerce"], keywords: ["retail turnover", "retail sales"], parentId: "trade-statistics" }),
  gov("services-index", "Services sector index", { categories: ["Economy & business", "Economic Sectors"], keywords: ["services index", "services sector"], parentId: "industry-sectors" }),
  gov("export-by-product", "Exports by product group", { categories: ["Commodities & metals", "Economy & business"], keywords: ["export by product", "export structure"], parentId: "trade-statistics" }),
  gov("import-by-product", "Imports by product group", { categories: ["Economy & business", "Commodities & metals"], keywords: ["import by product", "import structure"], parentId: "trade-statistics" }),
  gov("customs-statistics", "Customs & border trade", { categories: ["Commodities & metals", "Economy & business"], keywords: ["customs stat", "border trade"], parentId: "trade-statistics" }),
  gov("gold-reserves", "Gold & reserves statistics", { categories: ["Commodities & metals", "Financial Markets"], keywords: ["gold reserve", "precious metal"], parentId: "commodity-prices" }),
  gov("oil-gas-output", "Oil & gas production", { categories: ["Commodities & metals", "Economic Sectors"], keywords: ["oil production", "gas production"], parentId: "commodity-prices" }),

  // Environment & energy
  gov("air-quality", "Air quality monitoring", { categories: ["Environment", "Environment & climate"], keywords: ["air quality", "aqi", "pollution level"], parentId: "environment-stats" }),
  gov("water-resources", "Water resource statistics", { categories: ["Environment"], keywords: ["water resource", "water availability"], parentId: "environment-stats" }),
  gov("waste-management", "Waste management statistics", { categories: ["Environment"], keywords: ["waste management", "solid waste stat"], parentId: "environment-stats" }),
  gov("renewable-energy", "Renewable energy statistics", { categories: ["Environment & climate", "Economic Sectors"], keywords: ["renewable energy", "green energy stat"], parentId: "climate-data" }),
  gov("electricity-production", "Electricity production", { categories: ["Environment & climate", "Economic Sectors"], keywords: ["electricity production", "power generation"], parentId: "environment-stats" }),
  gov("carbon-emissions", "Carbon emissions data", { categories: ["Environment & climate"], keywords: ["carbon emissions", "co2 emissions"], parentId: "climate-data" }),
  gov("forest-resources", "Forest resource statistics", { categories: ["Environment"], keywords: ["forest resource", "forestry stat"], parentId: "environment-stats" }),
  gov("land-use", "Land use statistics", { categories: ["Environment", "Economic Sectors"], keywords: ["land use", "land cover stat"], parentId: "environment-stats" }),
  gov("weather-extremes", "Extreme weather events", { categories: ["Environment & climate"], keywords: ["extreme weather", "weather event stat"], parentId: "weather-forecast" }),

  // Transport & tourism
  gov("passenger-transport", "Passenger transport volumes", { categories: ["Transport", "Transportation"], keywords: ["passenger transport", "passenger traffic"], parentId: "transport-stats" }),
  gov("freight-transport", "Freight transport volumes", { categories: ["Transport", "Transportation"], keywords: ["freight transport", "cargo volume"], parentId: "transport-stats" }),
  gov("vehicle-registration", "Vehicle registration statistics", { categories: ["Transport", "Transportation"], keywords: ["vehicle registration", "car fleet stat"], parentId: "transport-stats" }),
  gov("road-network", "Road network statistics", { categories: ["Transport", "Transportation"], keywords: ["road network", "road length stat"], parentId: "transport-stats" }),
  gov("rail-freight", "Rail freight statistics", { categories: ["Transport", "Transportation"], keywords: ["rail freight", "railway cargo"], parentId: "transport-stats" }),
  gov("aviation-passengers", "Aviation passenger statistics", { categories: ["Transport", "Travel & mobility"], keywords: ["aviation passenger", "airport traffic"], parentId: "transport-stats" }),
  gov("tourism-arrivals", "Tourism arrival statistics", { categories: ["Travel & mobility", "Economy & business"], keywords: ["tourism arrivals", "visitor stat"], parentId: "travel-booking" }),
  gov("hotel-occupancy", "Hotel occupancy rates", { categories: ["Travel & mobility", "Economy & business"], keywords: ["hotel occupancy", "hospitality stat"], parentId: "tourism-arrivals" }),

  // Public safety & admin
  gov("crime-rates", "Crime rate statistics", { categories: ["Public Safety"], keywords: ["crime rate", "offence stat"], parentId: "public-safety" }),
  gov("road-accidents", "Road accident statistics", { categories: ["Public Safety", "Transport"], keywords: ["road accident", "traffic accident stat"], parentId: "public-safety" }),
  gov("fire-incidents", "Fire incident statistics", { categories: ["Public Safety"], keywords: ["fire incident", "fire stat"], parentId: "public-safety" }),
  gov("court-statistics", "Court & justice statistics", { categories: ["Public Safety", "Public Administration"], keywords: ["court stat", "judiciary data"], parentId: "public-safety" }),
  gov("civil-registry", "Civil registry data", { categories: ["Public Administration", "Government services"], keywords: ["civil registry", "vital records"], parentId: "gov-digital-services" }),
  gov("business-registry", "Business registry lookups", { categories: ["Public Administration", "Economy & business"], keywords: ["business registry", "company register"], parentId: "gov-digital-services" }),
  gov("licensing-permits", "Licensing & permits data", { categories: ["Public Administration", "Government services"], keywords: ["license registry", "permit stat"], parentId: "gov-digital-services" }),

  // Metadata & catalogue depth
  gov("api-catalogue", "Open API catalogue browse", { categories: ["Metadata", "Data Dictionaries", "Government data"], keywords: ["api catalogue", "dataset api list"], parentId: "metadata-catalog" }),
  gov("schema-documentation", "Dataset schema docs", { categories: ["Metadata", "Data Dictionaries"], keywords: ["schema documentation", "field definitions"], parentId: "metadata-catalog" }),
  gov("data-quality-scores", "Data quality indicators", { categories: ["Metadata", "Statistical Indicators"], keywords: ["data quality", "quality score"], parentId: "metadata-catalog" }),
  gov("statistical-methodology", "Statistical methodology notes", { categories: ["Metadata", "Statistical Indicators"], keywords: ["methodology", "stat method"], parentId: "indicator-definitions" }),
  gov("benchmark-revisions", "Benchmark & rebasing notes", { categories: ["Metadata", "National Accounts"], keywords: ["benchmark revision", "rebasing"], parentId: "dataset-revisions" }),

  // Commercial / build depth (properly tagged)
  feat({ id: "graphql-subscriptions", label: "GraphQL subscriptions", keywords: ["graphql subscription", "live subscription"], categories: ["Cloud & infrastructure", "Realtime"], capabilityTags: ["realtime-streams"] }),
  feat({ id: "sse-streaming", label: "Server-sent events", keywords: ["server sent events", "sse stream"], categories: ["Cloud & infrastructure", "Realtime"], capabilityTags: ["realtime-streams"] }),
  feat({ id: "ip-allowlisting", label: "IP allowlisting", keywords: ["ip allowlist", "ip whitelist"], categories: ["Cloud & infrastructure", "Auth & identity"] }),
  feat({ id: "mTLS-auth", label: "Mutual TLS authentication", keywords: ["mtls", "mutual tls"], categories: ["Banking & finance", "Auth & identity"] }),
  feat({ id: "pci-compliance", label: "PCI compliance patterns", keywords: ["pci dss", "pci compliance"], categories: ["Payments", "Banking & finance"], parentId: "checkout-payment" }),
  feat({ id: "fraud-detection", label: "Fraud detection signals", keywords: ["fraud detection", "risk scoring"], categories: ["Payments", "Banking & finance"], parentId: "checkout-payment" }),
  feat({ id: "3ds-authentication", label: "3-D Secure authentication", keywords: ["3ds", "3d secure"], categories: ["Payments"], parentId: "checkout-payment" }),
  feat({ id: "apple-pay-integration", label: "Apple Pay integration", keywords: ["apple pay"], categories: ["Payments"], parentId: "checkout-payment" }),
  feat({ id: "google-pay-integration", label: "Google Pay integration", keywords: ["google pay"], categories: ["Payments"], parentId: "checkout-payment" }),
  feat({ id: "terminal-pos", label: "POS terminal integration", keywords: ["pos terminal", "point of sale"], categories: ["Payments"], parentId: "checkout-payment" }),
  feat({ id: "escrow-payments", label: "Escrow payments", keywords: ["escrow payment", "held funds"], categories: ["Payments", "E-commerce"], parentId: "checkout-payment" }),
  feat({ id: "tip-payments", label: "Tip & gratuity payments", keywords: ["tip payment", "gratuity"], categories: ["Payments", "Food & delivery"], parentId: "checkout-payment" }),
  feat({ id: "chargeback-management", label: "Chargeback management", keywords: ["chargeback", "dispute management"], categories: ["Payments"], parentId: "refund-flow" }),
  feat({ id: "open-banking-ais", label: "Account information services", keywords: ["account information service", "ais open banking"], categories: ["Banking & finance"], parentId: "bank-accounts", capabilityTags: ["open-banking"] }),
  feat({ id: "open-banking-pis", label: "Payment initiation services", keywords: ["payment initiation", "pis open banking"], categories: ["Banking & finance", "Payments"], parentId: "bank-accounts", capabilityTags: ["open-banking"] }),
  feat({ id: "map-geofence-alerts", label: "Geofence entry alerts", keywords: ["geofence alert", "zone entry notification"], categories: ["Maps & location"], parentId: "geofencing" }),
  feat({ id: "fleet-telematics", label: "Fleet telematics", keywords: ["telematics", "fleet gps"], categories: ["Logistics & delivery", "Maps & location"], parentId: "logistics-routing", capabilityTags: ["fleet"] }),
  feat({ id: "route-optimization", label: "Route optimization (VRP)", keywords: ["route optimization", "vrp", "vehicle routing"], categories: ["Logistics & delivery", "Maps & location"], parentId: "route-planning" }),
  feat({ id: "isochrone-analysis", label: "Isochrone reach analysis", keywords: ["isochrone analysis", "reachability map"], categories: ["Maps & location"], parentId: "delivery-zones", capabilityTags: ["isochrone"] }),
  feat({ id: "matrix-routing", label: "Matrix routing batches", keywords: ["matrix routing", "many to many routes"], categories: ["Maps & location", "Logistics & delivery"], parentId: "delivery-eta", capabilityTags: ["distance-matrix"] }),
  feat({ id: "alice-voice-skill", label: "Alice voice skill", keywords: ["alice skill", "yandex alice"], categories: ["AI", "Communications"], parentId: "ai-assistant", capabilityTags: ["voice-assistant"], providers: ["yandex"] }),
  feat({ id: "yandexgpt-prompts", label: "YandexGPT prompt templates", keywords: ["yandexgpt prompt", "prompt template"], categories: ["AI"], parentId: "ai-assistant", providers: ["yandex"] }),
  feat({ id: "image-generation", label: "AI image generation", keywords: ["image generation", "text to image"], categories: ["AI"], parentId: "ai-assistant" }),
  feat({ id: "sentiment-analysis", label: "Sentiment analysis", keywords: ["sentiment analysis", "opinion mining"], categories: ["AI", "Communications"], parentId: "ai-assistant" }),
  feat({ id: "named-entity-extraction", label: "Named entity extraction", keywords: ["named entity", "ner extraction"], categories: ["AI", "Data & enrichment"], parentId: "ai-assistant" }),
  feat({ id: "rag-retrieval", label: "RAG document retrieval", keywords: ["rag retrieval", "retrieval augmented"], categories: ["AI", "Data & enrichment"], parentId: "embeddings-search" }),
  feat({ id: "wildberries-seller", label: "Wildberries seller API", keywords: ["wildberries seller", "wb api"], categories: ["E-commerce"], parentId: "marketplace-sync", providers: ["wildberries"] }),
  feat({ id: "ozon-seller", label: "Ozon seller integration", keywords: ["ozon seller", "ozon api"], categories: ["E-commerce"], parentId: "marketplace-sync", providers: ["ozon"] }),
  feat({ id: "yandex-market-seller", label: "Yandex Market seller", keywords: ["yandex market seller"], categories: ["E-commerce"], parentId: "marketplace-sync", providers: ["yandex market"] }),
  feat({ id: "cdek-tracking", label: "CDEK parcel tracking", keywords: ["cdek tracking", "cdek api"], categories: ["Logistics & delivery"], parentId: "parcel-shipping", providers: ["cdek"] }),
  feat({ id: "kazpost-tracking", label: "Kazpost tracking", keywords: ["kazpost tracking"], categories: ["Logistics & delivery"], parentId: "parcel-shipping", providers: ["kazpost"] }),
  feat({ id: "indriver-api", label: "inDriver partner API", keywords: ["indriver api", "indriver partner"], categories: ["Travel & mobility"], parentId: "ride-hailing", providers: ["indriver"] }),
  feat({ id: "arbuz-integration", label: "Arbuz grocery API", keywords: ["arbuz api", "arbuz integration"], categories: ["Food & delivery", "E-commerce"], parentId: "grocery-delivery", providers: ["arbuz"] }),
  feat({ id: "sigex-signing", label: "SIGEX document signing", keywords: ["sigex signing", "sigex api"], categories: ["Auth & identity", "Government services"], parentId: "esignature", providers: ["sigex"] }),
  feat({ id: "npck-open-banking", label: "NPCK open banking", keywords: ["npck open banking", "npck api"], categories: ["Banking & finance", "Payments"], parentId: "bank-accounts", providers: ["npck"] }),
  feat({ id: "freedompay-checkout", label: "FreedomPay checkout", keywords: ["freedompay checkout"], categories: ["Payments"], parentId: "checkout-payment", providers: ["freedompay"] }),
  feat({ id: "kaspi-merchant", label: "Kaspi merchant payments", keywords: ["kaspi merchant", "kaspi pay api"], categories: ["Payments"], parentId: "checkout-payment", providers: ["kaspi"] }),
  feat({ id: "beeline-sms", label: "Beeline SMS gateway", keywords: ["beeline sms"], categories: ["Communications"], parentId: "sms-otp", providers: ["beeline"] }),
  feat({ id: "kcell-sms", label: "Kcell SMS gateway", keywords: ["kcell sms"], categories: ["Communications"], parentId: "sms-otp", providers: ["kcell"] }),
  feat({ id: "tele2-sms", label: "Tele2 SMS gateway", keywords: ["tele2 sms"], categories: ["Communications"], parentId: "sms-otp", providers: ["tele2"] }),
  feat({ id: "yandex-metrica-events", label: "Yandex Metrica events", keywords: ["metrica events", "yandex metrica api"], categories: ["Communications"], parentId: "analytics-tracking", providers: ["yandex"] }),
  feat({ id: "yandex-direct-campaigns", label: "Yandex Direct campaigns", keywords: ["yandex direct api"], categories: ["Communications"], parentId: "ads-campaigns", providers: ["yandex"] }),
  feat({ id: "yandex-cloud-compute", label: "Yandex Cloud compute", keywords: ["yandex cloud compute", "yc compute"], categories: ["Cloud & infrastructure"], parentId: "cloud-hosting", providers: ["yandex"] }),
  feat({ id: "yandex-cloud-storage", label: "Yandex Cloud storage", keywords: ["yandex cloud storage", "yc s3"], categories: ["Cloud & infrastructure"], parentId: "cloud-hosting", capabilityTags: ["object-storage"], providers: ["yandex"] }),
  feat({ id: "2gis-routing", label: "2GIS routing API", keywords: ["2gis routing", "2gis directions"], categories: ["Maps & location"], parentId: "route-planning", providers: ["2gis"] }),
  feat({ id: "2gis-places", label: "2GIS places search", keywords: ["2gis places", "2gis catalog"], categories: ["Maps & location"], parentId: "poi-search", providers: ["2gis"] }),
  feat({ id: "nbk-rates-feed", label: "NBK official rates feed", keywords: ["nbk rates", "national bank rates"], categories: ["Financial Markets", "Finance"], parentId: "fx-rates", providers: ["nbk"] }),
  feat({ id: "statgov-indicators", label: "stat.gov indicator API", keywords: ["stat.gov indicator", "bureau stat"], categories: ["Government data", "Statistical Indicators"], parentId: "gov-open-data", providers: ["stat.gov", "bureau"] }),
  feat({ id: "dataegov-datasets", label: "data.egov dataset API", keywords: ["data.egov dataset"], categories: ["Government data", "Metadata"], parentId: "gov-open-data", providers: ["data.egov", "egov"] }),
  feat({ id: "esf-invoicing", label: "ESF e-invoicing", keywords: ["esf invoice", "electronic invoice kz"], categories: ["E-invoicing & tax"], parentId: "tax-invoicing", providers: ["esf", "kgd"] }),
  feat({ id: "crypto-wallet", label: "Crypto wallet integration", keywords: ["crypto wallet", "digital wallet crypto"], categories: ["Crypto"], parentId: "crypto-trading" }),
  feat({ id: "crypto-price-feed", label: "Crypto price feed", keywords: ["crypto price feed", "token price api"], categories: ["Crypto"], parentId: "crypto-trading" }),
  feat({ id: "company-enrichment", label: "Company data enrichment", keywords: ["company enrichment", "business lookup"], categories: ["Data & enrichment"], parentId: "data-enrichment" }),
  feat({ id: "address-enrichment", label: "Address data enrichment", keywords: ["address enrichment"], categories: ["Data & enrichment", "Maps & location"], parentId: "data-enrichment" }),
  feat({ id: "identity-verification", label: "Identity verification API", keywords: ["identity verification", "id verification"], categories: ["Data & enrichment", "Auth & identity"], parentId: "data-enrichment" }),
  feat({ id: "live-dashboard", label: "Live updating dashboards", keywords: ["live dashboard", "realtime dashboard"], categories: ["Realtime", "Cloud & infrastructure"], parentId: "realtime-streams" }),
  feat({ id: "ops-alerting", label: "Ops alerting rules", keywords: ["ops alerting", "on-call alert"], categories: ["Realtime", "Cloud & infrastructure"], parentId: "monitoring-alerts" }),
  feat({ id: "prayer-notifications", label: "Prayer time notifications", keywords: ["prayer notification", "namaz reminder"], categories: ["Other portals"], parentId: "prayer-times", providers: ["aladhan"] }),
  feat({ id: "islamic-calendar", label: "Islamic calendar dates", keywords: ["islamic calendar", "hijri date"], categories: ["Other portals"], parentId: "prayer-times", providers: ["aladhan"] }),
  feat({ id: "model-serving", label: "Model serving & deployment", keywords: ["model serving", "model deployment"], categories: ["AI", "Cloud & infrastructure"], parentId: "ai-assistant" }),
  feat({ id: "prompt-engineering", label: "Prompt engineering templates", keywords: ["prompt engineering", "prompt design"], categories: ["AI"], parentId: "yandexgpt-prompts" }),
  feat({ id: "vector-database", label: "Vector database search", keywords: ["vector database", "vector store"], categories: ["AI", "Data & enrichment", "Cloud & infrastructure"], parentId: "embeddings-search" }),
  feat({ id: "agent-orchestration", label: "AI agent orchestration", keywords: ["ai agent", "agent orchestration"], categories: ["AI"], parentId: "ai-assistant" }),
  feat({ id: "kubernetes-hosting", label: "Kubernetes cluster hosting", keywords: ["kubernetes", "k8s cluster"], categories: ["Cloud & infrastructure"], parentId: "cloud-hosting" }),
  feat({ id: "terraform-iac", label: "Infrastructure as code", keywords: ["terraform", "infrastructure as code"], categories: ["Cloud & infrastructure"], parentId: "cloud-hosting" }),
  feat({ id: "log-aggregation", label: "Centralized log aggregation", keywords: ["log aggregation", "centralized logging"], categories: ["Cloud & infrastructure"], parentId: "monitoring-alerts" }),
  feat({ id: "portal-authentication", label: "Portal user authentication", keywords: ["portal auth", "portal login"], categories: ["Other portals", "Auth & identity"], parentId: "user-auth" }),
  feat({ id: "portal-analytics", label: "Portal usage analytics", keywords: ["portal analytics", "portal metrics"], categories: ["Other portals", "Communications"], parentId: "analytics-tracking" }),
  feat({ id: "widget-customization", label: "Widget theming & customization", keywords: ["widget customization", "widget theme"], categories: ["Other portals"], parentId: "embed-widget" }),
  feat({ id: "vat-reporting", label: "VAT reporting & filing", keywords: ["vat reporting", "vat filing"], categories: ["E-invoicing & tax"], parentId: "vat-calculation" }),
  feat({ id: "e-invoice-archive", label: "E-invoice archive & audit", keywords: ["invoice archive", "e-invoice audit"], categories: ["E-invoicing & tax"], parentId: "tax-invoicing" }),
  feat({ id: "tax-reconciliation", label: "Tax reconciliation", keywords: ["tax reconciliation", "tax matching"], categories: ["E-invoicing & tax", "Banking & finance"], parentId: "tax-invoicing" }),
  feat({ id: "warehouse-receipts", label: "Virtual warehouse receipts", keywords: ["virtual warehouse", "warehouse receipt esf"], categories: ["E-invoicing & tax"], parentId: "esf-invoicing" }),
  feat({ id: "snt-documents", label: "SNT accompanying invoices", keywords: ["snt document", "shipping note tax"], categories: ["E-invoicing & tax"], parentId: "tax-invoicing" }),
  feat({ id: "audit-trail-export", label: "Compliance audit trail export", keywords: ["audit trail", "compliance export"], categories: ["E-invoicing & tax", "Banking & finance"], parentId: "tax-invoicing" }),
  feat({ id: "invoice-numbering", label: "Invoice numbering sequences", keywords: ["invoice numbering", "invoice sequence"], categories: ["E-invoicing & tax"], parentId: "invoice-generation" }),
  feat({ id: "invoice-templates", label: "Invoice templates", keywords: ["invoice template", "bill template"], categories: ["E-invoicing & tax"], parentId: "invoice-generation" }),
  feat({ id: "credit-note-issuance", label: "Credit note issuance", keywords: ["credit note", "credit memo"], categories: ["E-invoicing & tax"], parentId: "tax-invoicing" }),
  feat({ id: "debit-note-issuance", label: "Debit note issuance", keywords: ["debit note"], categories: ["E-invoicing & tax"], parentId: "tax-invoicing" }),
  feat({ id: "buyer-invoice-inbox", label: "Buyer invoice inbox", keywords: ["buyer invoice", "invoice inbox"], categories: ["E-invoicing & tax"], parentId: "tax-invoicing" }),
  feat({ id: "seller-invoice-outbox", label: "Seller invoice outbox", keywords: ["seller invoice", "invoice outbox"], categories: ["E-invoicing & tax"], parentId: "tax-invoicing" }),
  feat({ id: "invoice-status-tracking", label: "Invoice status tracking", keywords: ["invoice status", "invoice state"], categories: ["E-invoicing & tax"], parentId: "payment-status" }),
  feat({ id: "tax-code-lookup", label: "Tax code lookup", keywords: ["tax code", "vat code lookup"], categories: ["E-invoicing & tax"], parentId: "vat-calculation" }),
  feat({ id: "counterparty-validation", label: "Counterparty validation", keywords: ["counterparty validation", "buyer tin check"], categories: ["E-invoicing & tax", "Data & enrichment"], parentId: "data-enrichment" }),
  feat({ id: "digital-signature-invoice", label: "Digitally signed invoices", keywords: ["signed invoice", "digital signature invoice"], categories: ["E-invoicing & tax", "Auth & identity"], parentId: "esignature" }),
  feat({ id: "erp-invoice-sync", label: "ERP invoice sync", keywords: ["erp sync", "erp invoice"], categories: ["E-invoicing & tax", "E-commerce"], parentId: "tax-invoicing" }),
  feat({ id: "inventory-writeoff", label: "Inventory write-off docs", keywords: ["inventory writeoff", "stock write off"], categories: ["E-invoicing & tax"], parentId: "esf-invoicing" }),
  feat({ id: "excise-reporting", label: "Excise tax reporting", keywords: ["excise tax", "excise reporting"], categories: ["E-invoicing & tax"], parentId: "tax-revenue" }),
  feat({ id: "turnover-declaration", label: "Turnover declarations", keywords: ["turnover declaration", "sales declaration"], categories: ["E-invoicing & tax"], parentId: "tax-revenue" }),
  feat({ id: "fiscal-receipts", label: "Fiscal receipt integration", keywords: ["fiscal receipt", "fiscal printer"], categories: ["E-invoicing & tax", "Payments"], parentId: "checkout-payment" }),
  feat({ id: "cash-register-sync", label: "Cash register sync", keywords: ["cash register", "pos fiscal"], categories: ["E-invoicing & tax", "Payments"], parentId: "terminal-pos" }),
  feat({ id: "invoice-pdf-export", label: "Invoice PDF export", keywords: ["invoice pdf", "pdf invoice"], categories: ["E-invoicing & tax"], parentId: "pdf-reports" }),
  feat({ id: "bulk-invoice-upload", label: "Bulk invoice upload", keywords: ["bulk invoice", "batch invoice upload"], categories: ["E-invoicing & tax"], parentId: "bulk-read" }),
  feat({ id: "invoice-webhooks", label: "Invoice status webhooks", keywords: ["invoice webhook", "invoice callback"], categories: ["E-invoicing & tax"], parentId: "webhook-callbacks" }),
  feat({ id: "tax-period-close", label: "Tax period close reports", keywords: ["tax period close", "period closing"], categories: ["E-invoicing & tax"], parentId: "vat-reporting" }),
  feat({ id: "withholding-tax", label: "Withholding tax calculation", keywords: ["withholding tax", "wht calc"], categories: ["E-invoicing & tax", "Banking & finance"], parentId: "vat-calculation" }),
  feat({ id: "contract-invoice-link", label: "Contract-to-invoice linking", keywords: ["contract invoice", "contract billing"], categories: ["E-invoicing & tax"], parentId: "invoice-generation" }),
];
