/**
 * Product feature ontology — grouping axis for API suggest (not provider domains).
 */

export const FEATURES = [
  {
    id: "address-autocomplete",
    label: "Address autocomplete",
    parentId: "address-geocoding",
    why: "Help users pick valid addresses quickly as they type",
    where: "Checkout delivery field, signup address, search bar with typeahead",
    keywords: [
      "autocomplete", "typeahead", "suggest", "address input", "address field", "geosuggest",
    ],
    capabilityTags: ["address-autocomplete", "geocode"],
    categories: ["Maps & location"],
    providers: ["2gis", "yandex"],
  },
  {
    id: "forward-geocode",
    label: "Address → coordinates",
    parentId: "address-geocoding",
    why: "Turn street addresses into map coordinates for routing and pins",
    where: "After address submit, order confirmation, geocoding batch jobs",
    keywords: [
      "geocode", "geocoder", "geocoordinator", "coordinates", "lat", "lng", "forward geocode",
      "address to coordinates",
    ],
    capabilityTags: ["geocode", "forward-geocode"],
    categories: ["Maps & location"],
    providers: ["2gis", "yandex"],
  },
  {
    id: "reverse-geocode",
    label: "Coordinates → address",
    parentId: "address-geocoding",
    why: "Show human-readable addresses from map pins or GPS points",
    where: "Map pin drop, courier GPS trace, location share screen",
    keywords: ["reverse geocode", "reverse geocoding", "pin drop", "map pin", "gps to address"],
    capabilityTags: ["reverse-geocode", "geocode"],
    categories: ["Maps & location"],
    providers: ["2gis", "yandex"],
  },
  {
    id: "address-geocoding",
    label: "Address lookup",
    parentId: null,
    why: "Convert between addresses and map coordinates",
    where: "Address forms, map screens, delivery location capture",
    keywords: [
      "address", "geocoding", "geolocation", "location", "maps address", "coordinates",
    ],
    capabilityTags: ["geocode", "reverse-geocode", "forward-geocode", "address-autocomplete"],
    categories: ["Maps & location"],
    providers: ["2gis", "yandex"],
  },
  {
    id: "poi-search",
    label: "Places & POI search",
    parentId: null,
    why: "Find businesses, landmarks and organizations on a map",
    where: "Store locator, nearby search, restaurant browse map",
    keywords: ["poi", "places", "organization", "nearby", "catalog", "2gis places", "store locator"],
    capabilityTags: ["poi-search", "places"],
    categories: ["Maps & location"],
    providers: ["2gis", "yandex"],
  },
  {
    id: "delivery-eta",
    label: "Delivery time estimates",
    parentId: "logistics-routing",
    why: "Show how long delivery or travel will take between stops",
    where: "Checkout ETA, courier dispatch board, order tracking",
    keywords: [
      "eta", "delivery time", "courier", "distance matrix", "travel time", "duration", "arrival time",
    ],
    capabilityTags: ["distance-matrix", "delivery-eta", "routing"],
    categories: ["Maps & location", "Travel & mobility", "Logistics & delivery"],
    providers: ["2gis", "yandex"],
  },
  {
    id: "route-planning",
    label: "Route planning",
    parentId: "logistics-routing",
    why: "Draw drive, walk or bike routes between points",
    where: "Courier navigation, driver app, trip planner map",
    keywords: ["routing", "route", "navigation", "directions", "drive", "walk", "bike"],
    capabilityTags: ["routing", "route-planning"],
    categories: ["Maps & location", "Travel & mobility"],
    providers: ["2gis", "yandex", "indriver"],
  },
  {
    id: "delivery-zones",
    label: "Delivery coverage zones",
    parentId: "logistics-routing",
    why: "Define where you can deliver or serve customers on a map",
    where: "Delivery zone settings, store coverage map, fee zone rules",
    keywords: ["isochrone", "coverage", "delivery zone", "service area", "reachable"],
    capabilityTags: ["isochrone", "delivery-zones"],
    categories: ["Maps & location"],
    providers: ["2gis", "yandex"],
  },
  {
    id: "logistics-routing",
    label: "Logistics & routing",
    parentId: null,
    why: "Plan routes, ETAs and delivery coverage for couriers and fleets",
    where: "Dispatch, fleet ops, delivery fee and ETA flows",
    keywords: ["logistics", "fleet", "courier routing", "last mile", "dispatch"],
    capabilityTags: ["routing", "distance-matrix", "delivery-eta", "isochrone"],
    categories: ["Maps & location", "Logistics & delivery", "Travel & mobility"],
    providers: ["2gis", "yandex"],
  },
  {
    id: "checkout-payment",
    label: "Checkout payments",
    parentId: null,
    why: "Charge customers when they confirm an order or subscription",
    where: "Checkout confirm step, pay button, invoice settlement",
    keywords: [
      "pay", "payment", "payments", "checkout", "kaspi", "freedompay", "wooppay", "paybox", "qiwi",
      "card", "acquiring", "merchant", "pos", "qr pay",
    ],
    capabilityTags: ["checkout-payment", "qr-payment", "wallet-payment"],
    categories: ["Payments", "Banking & finance"],
    providers: ["kaspi", "freedompay", "wooppay", "paybox", "qiwi", "halyk", "npck"],
    negativeKeywords: ["exchange rate", "statistics", "population"],
  },
  {
    id: "wallet-payout",
    label: "Wallet & payouts",
    parentId: null,
    why: "Send money to users, sellers or bank accounts",
    where: "Seller payouts, refunds, B2C transfers, wallet top-up",
    keywords: ["payout", "transfer", "wallet", "withdraw", "imps", "disbursement"],
    capabilityTags: ["wallet-payout", "bank-transfer"],
    categories: ["Payments", "Banking & finance"],
    providers: ["npck", "kaspi", "halyk"],
  },
  {
    id: "fx-rates",
    label: "Exchange rates & FX",
    parentId: null,
    why: "Show official or market FX rates in dashboards and converters",
    where: "Currency converter, finance dashboard, pricing screens",
    keywords: ["fx", "exchange rate", "currency", "nbk rate", "forex", "convert currency"],
    capabilityTags: ["fx-rates", "exchange-rates"],
    categories: ["Banking & finance", "Finance", "Financial Markets", "Prices"],
    providers: ["nbk", "nationalbank"],
    negativeKeywords: ["checkout", "pay", "horse", "student app"],
  },
  {
    id: "bank-accounts",
    label: "Bank account data",
    parentId: null,
    why: "Read balances and transactions after user consent",
    where: "Open banking onboarding, account aggregation, PFM apps",
    keywords: ["open banking", "account balance", "transactions", "bank account", "npck", "consent"],
    capabilityTags: ["bank-accounts", "open-banking"],
    categories: ["Banking & finance", "Payments"],
    providers: ["npck", "halyk", "forte"],
  },
  {
    id: "user-auth",
    label: "Sign-in & identity",
    parentId: null,
    why: "Let users register and log in securely",
    where: "Registration screen, login modal, SSO redirect",
    keywords: ["auth", "login", "signup", "oauth", "identity", "yandex id", "finid", "kyc", "verify"],
    capabilityTags: ["user-auth", "oauth", "identity"],
    categories: ["Auth & identity", "Government services"],
    providers: ["yandex", "sigex", "egov", "npck"],
  },
  {
    id: "esignature",
    label: "E-signature & EDS",
    parentId: null,
    why: "Sign contracts and documents with legal digital signatures",
    where: "Contract signing flow, HR onboarding, gov form submit",
    keywords: ["signature", "eds", "sigex", "e-sign", "digital signature", "document sign"],
    capabilityTags: ["esignature", "eds"],
    categories: ["Auth & identity", "Government services"],
    providers: ["sigex", "egov"],
  },
  {
    id: "sms-otp",
    label: "SMS & OTP",
    parentId: null,
    why: "Send one-time codes and transactional SMS",
    where: "Login OTP step, order updates, phone verification",
    keywords: ["sms", "otp", "text message", "verification code", "beeline", "kcell", "tele2"],
    capabilityTags: ["sms-otp", "sms"],
    categories: ["Communications"],
    providers: ["beeline", "kcell", "tele2", "altel"],
  },
  {
    id: "food-delivery-partner",
    label: "Food delivery integration",
    parentId: null,
    why: "Hand off orders to a delivery or restaurant network",
    where: "Post-checkout handoff, restaurant partner portal",
    keywords: ["glovo", "wolt", "food delivery", "restaurant delivery", "order food"],
    capabilityTags: ["food-delivery", "delivery-partner"],
    categories: ["Food & delivery", "E-commerce"],
    providers: ["glovo", "wolt", "chocofamily"],
  },
  {
    id: "parcel-shipping",
    label: "Parcel shipping",
    parentId: null,
    why: "Ship parcels and track packages nationally",
    where: "Shipping label creation, tracking page, returns flow",
    keywords: ["parcel", "shipping", "cdek", "kazpost", "track package", "logistics"],
    capabilityTags: ["parcel-shipping", "tracking"],
    categories: ["Logistics & delivery", "E-commerce"],
    providers: ["cdek", "kazpost"],
  },
  {
    id: "marketplace-sync",
    label: "Marketplace & catalog sync",
    parentId: null,
    why: "Sync products and orders with marketplaces",
    where: "Seller dashboard, inventory sync jobs, order webhooks",
    keywords: ["marketplace", "wildberries", "ozon", "seller", "sku", "inventory", "ecommerce"],
    capabilityTags: ["marketplace-sync", "catalog-sync"],
    categories: ["E-commerce"],
    providers: ["wildberries", "ozon", "yandex market"],
  },
  {
    id: "travel-booking",
    label: "Travel & tickets",
    parentId: null,
    why: "Search and book flights, trains or buses",
    where: "Travel search results, booking checkout, ticket wallet",
    keywords: ["flight", "train", "ticket", "aviata", "air astana", "railways", "ktz", "travel book"],
    capabilityTags: ["travel-booking", "flights", "trains"],
    categories: ["Travel & mobility", "Transport"],
    providers: ["aviata", "air astana", "flyarystan", "scat", "ktz"],
  },
  {
    id: "weather-forecast",
    label: "Weather forecasts",
    parentId: null,
    why: "Show weather for planning screens and logistics",
    where: "Home dashboard, delivery delay alerts, agriculture views",
    keywords: ["weather", "forecast", "kazhydromet", "temperature", "climate", "rain"],
    capabilityTags: ["weather-forecast"],
    categories: ["Environment & climate", "Environment"],
    providers: ["kazhydromet"],
  },
  {
    id: "gov-open-data",
    label: "Government open data",
    parentId: null,
    why: "Use verified public statistics and registry datasets",
    where: "Analytics dashboards, research tools, civic apps",
    keywords: [
      "open data", "statistics", "egov", "dataset", "stat.gov", "government data", "data.egov",
    ],
    capabilityTags: ["gov-open-data", "statistics"],
    categories: [
      "Government data",
      "Statistical Indicators",
      "Public Administration",
      "Data Dictionaries",
      "Metadata",
    ],
    providers: ["egov", "stat.gov", "data.egov", "bureau"],
    negativeKeywords: ["checkout", "geocode", "payment", "horse riding"],
  },
  {
    id: "population-stats",
    label: "Population & demography",
    parentId: "gov-open-data",
    why: "Show population, births, and demographic indicators",
    where: "Civic dashboards, market sizing, research reports",
    keywords: ["population", "demography", "births", "census", "households count", "residents"],
    capabilityTags: ["population-stats", "gov-open-data"],
    categories: ["Demography", "Population & society"],
    providers: ["bureau", "egov", "stat.gov"],
  },
  {
    id: "housing-stats",
    label: "Housing & property data",
    parentId: "gov-open-data",
    why: "Analyze housing stock, construction, and property indicators",
    where: "Real-estate dashboards, urban planning tools, valuation models",
    keywords: ["housing", "property data", "apartment stock", "cadastral", "real estate stats", "rent index"],
    capabilityTags: ["housing-stats"],
    categories: ["Housing & property", "Property"],
    providers: ["bureau", "egov"],
  },
  {
    id: "education-stats",
    label: "Education statistics",
    parentId: "gov-open-data",
    why: "Use school, university and enrollment datasets",
    where: "Education dashboards, campus planning, NGO reports",
    keywords: ["education", "school", "university", "enrollment", "literacy", "education stats"],
    capabilityTags: ["education-stats"],
    categories: ["Education"],
    providers: ["bureau", "egov", "moe"],
    negativeKeywords: ["student app", "homework app", "horse"],
  },
  {
    id: "health-stats",
    label: "Health & medical stats",
    parentId: "gov-open-data",
    why: "Consume hospital, disease and public-health indicators",
    where: "Health dashboards, epidemic monitors, NGO tooling",
    keywords: ["health", "hospital", "clinic", "covid", "medical stats", "blood donation", "pharmacy stats"],
    capabilityTags: ["health-stats"],
    categories: ["Health", "Healthcare"],
    providers: ["bureau", "egov", "moh"],
  },
  {
    id: "labour-stats",
    label: "Labour market data",
    parentId: "gov-open-data",
    why: "Track unemployment, wages and workforce indicators",
    where: "HR analytics, economic dashboards, policy tools",
    keywords: ["labour", "labor", "unemployment", "wages", "workforce", "employment", "jobs stats"],
    capabilityTags: ["labour-stats"],
    categories: ["Labour Markets", "Work & income"],
    providers: ["bureau", "egov"],
  },
  {
    id: "price-indices",
    label: "Prices & inflation",
    parentId: null,
    why: "Show CPI, PPI, fuel and consumer price indices",
    where: "Inflation dashboards, pricing tools, cost-of-living screens",
    keywords: ["cpi", "ppi", "inflation", "fuel price", "consumer price", "price index"],
    capabilityTags: ["price-indices", "fuel-prices"],
    categories: ["Prices", "National Accounts"],
    providers: ["bureau", "nbk"],
  },
  {
    id: "public-safety",
    label: "Public safety data",
    parentId: "gov-open-data",
    why: "Use crime, fire and emergency open datasets",
    where: "Safety maps, civic dashboards, insurance risk tools",
    keywords: ["crime", "public safety", "police", "fire", "emergency stats"],
    capabilityTags: ["public-safety"],
    categories: ["Public Safety"],
    providers: ["bureau", "egov"],
  },
  {
    id: "national-accounts",
    label: "Economy & national accounts",
    parentId: "gov-open-data",
    why: "Access GDP and macroeconomic indicators",
    where: "Macro dashboards, research portals, investment briefings",
    keywords: ["gdp", "national accounts", "economic indicators", "macro", "sectors"],
    capabilityTags: ["national-accounts", "gov-open-data"],
    categories: ["National Accounts", "Economic Sectors", "Economy & business"],
    providers: ["bureau", "nbk"],
  },
  {
    id: "household-stats",
    label: "Household income & expenditure",
    parentId: "gov-open-data",
    why: "Analyze household surveys and living standards",
    where: "Policy dashboards, poverty research, economic planning",
    keywords: ["household", "income survey", "hies", "expenditure", "living standards"],
    capabilityTags: ["household-stats"],
    categories: ["Households"],
    providers: ["bureau", "egov"],
  },
  {
    id: "workplace-productivity",
    label: "Workplace & collaboration",
    parentId: null,
    why: "Calendar, forms, email and project tools for teams",
    where: "Internal admin, HR onboarding, team scheduling",
    keywords: ["calendar", "forms", "tracker", "business email", "yandex 360", "connect"],
    capabilityTags: ["calendar-scheduling", "project-tracking", "forms-surveys", "business-email", "org-directory"],
    categories: ["Communications"],
    providers: ["yandex"],
  },
  {
    id: "ride-hailing",
    label: "Ride-hailing",
    parentId: null,
    why: "Request on-demand rides and track drivers",
    where: "Ride request screen, driver ETA map, trip history",
    keywords: ["taxi", "ride hail", "ride-hailing", "indriver", "yandex go", "cab"],
    capabilityTags: ["ride-hailing"],
    categories: ["Travel & mobility"],
    providers: ["indriver", "yandex"],
  },
  {
    id: "grocery-delivery",
    label: "Grocery delivery",
    parentId: null,
    why: "Integrate grocery / quick-commerce partners",
    where: "Post-checkout grocery handoff, partner catalog sync",
    keywords: ["grocery", "arbuz", "lavka", "supermarket delivery", "quick commerce"],
    capabilityTags: ["grocery-delivery"],
    categories: ["Food & delivery", "E-commerce"],
    providers: ["arbuz", "yandex", "chocofamily"],
  },
  {
    id: "map-display",
    label: "Map display",
    parentId: null,
    why: "Render interactive or static maps in the product",
    where: "Map screen, store locator UI, tracking map widget",
    keywords: ["map display", "static map", "map tiles", "mapkit", "show map", "map widget"],
    capabilityTags: ["map-display", "static-maps"],
    categories: ["Maps & location"],
    providers: ["2gis", "yandex"],
  },
  {
    id: "device-location",
    label: "Device location",
    parentId: null,
    why: "Resolve approximate device GPS / network location",
    where: "“Near me” button, location permission onboarding",
    keywords: ["device location", "locator", "gps", "user location", "near me"],
    capabilityTags: ["device-location"],
    categories: ["Maps & location"],
    providers: ["yandex", "2gis"],
  },
  {
    id: "speech-ai",
    label: "Speech & translation",
    parentId: null,
    why: "Transcribe speech, synthesize voice, or translate text",
    where: "Voice input, IVR, multilingual content screens",
    keywords: ["speech", "stt", "tts", "speechkit", "translate", "translation", "voice"],
    capabilityTags: ["speech-to-text", "text-to-speech", "translation"],
    categories: ["AI"],
    providers: ["yandex"],
  },
  {
    id: "computer-vision",
    label: "Computer vision",
    parentId: null,
    why: "OCR and image understanding for documents or photos",
    where: "ID scan, receipt OCR, photo moderation",
    keywords: ["vision", "ocr", "computer vision", "image recognition", "document scan"],
    capabilityTags: ["computer-vision"],
    categories: ["AI"],
    providers: ["yandex"],
  },
  {
    id: "prayer-times",
    label: "Prayer times",
    parentId: null,
    why: "Show Islamic prayer schedules for cities",
    where: "Home widget, reminder notifications, mosque apps",
    keywords: ["prayer", "salah", "namaz", "aladhan", "azan"],
    capabilityTags: ["prayer-times"],
    categories: ["Other portals"],
    providers: ["aladhan"],
  },
  {
    id: "ai-assistant",
    label: "AI & chat features",
    parentId: null,
    why: "Add LLM assistants, search ranking or generated content",
    where: "In-app chat, help bot, content generation panel",
    keywords: ["ai", "llm", "gpt", "yandexgpt", "chatbot", "assistant", "nlp"],
    capabilityTags: ["ai-assistant", "llm"],
    categories: ["AI"],
    providers: ["yandex"],
  },
  {
    id: "analytics-tracking",
    label: "Analytics & measurement",
    parentId: null,
    why: "Measure product usage and marketing performance",
    where: "App install, page views, conversion funnels",
    keywords: ["analytics", "metrica", "appmetrica", "tracking", "measurement"],
    capabilityTags: ["analytics-tracking"],
    categories: ["Communications"],
    providers: ["yandex"],
  },
  {
    id: "ads-campaigns",
    label: "Ads & campaigns",
    parentId: null,
    why: "Run and manage advertising campaigns",
    where: "Marketing dashboard, campaign creation, ad spend reports",
    keywords: ["ads", "advertising", "yandex direct", "campaign", "marketing"],
    capabilityTags: ["ads-campaigns"],
    categories: ["Communications"],
    providers: ["yandex"],
  },
  {
    id: "tax-invoicing",
    label: "Tax & e-invoicing",
    parentId: null,
    why: "Issue electronic invoices and sync with tax systems",
    where: "Invoice generation, ERP sync, VAT reporting",
    keywords: ["tax", "esf", "e-invoice", "vat", "kgd", "electronic invoice"],
    capabilityTags: ["tax-invoicing", "e-invoice"],
    categories: ["E-invoicing & tax"],
    providers: ["kgd", "esf"],
  },
  {
    id: "cloud-hosting",
    label: "Cloud & hosting",
    parentId: null,
    why: "Run backend infra, storage and managed services",
    where: "DevOps setup, file storage, compute provisioning",
    keywords: ["cloud", "hosting", "storage", "yandex cloud", "ps.kz", "server", "kubernetes", "yandex disk"],
    capabilityTags: ["cloud-hosting", "object-storage", "serverless"],
    categories: ["Cloud & infrastructure"],
    providers: ["yandex", "ps", "beeline"],
  },
  {
    id: "site-search",
    label: "On-site & web search",
    parentId: null,
    why: "Add site search or programmatic web search",
    where: "Help center search bar, knowledge base, research tool",
    keywords: ["site search", "web search", "yandex xml", "search widget", "on-site search"],
    capabilityTags: ["site-search", "web-search"],
    categories: ["Communications", "AI"],
    providers: ["yandex"],
  },
  {
    id: "seo-webmaster",
    label: "SEO & webmaster tools",
    parentId: null,
    why: "Monitor indexing, structured data and turbo pages",
    where: "Marketing SEO dashboard, content publishing pipeline",
    keywords: ["webmaster", "seo", "indexing", "turbo pages", "structured data"],
    capabilityTags: ["seo-webmaster"],
    categories: ["Communications"],
    providers: ["yandex"],
  },
];

/** Whole-product shortcuts — boost features when prompt matches a known app type. */
export const PRODUCT_RECIPES = [
  {
    id: "food-delivery",
    match: ["food delivery", "delivery app", "restaurant app", "order food", "glovo", "wolt", "courier app"],
    features: ["address-autocomplete", "checkout-payment", "delivery-eta", "route-planning", "food-delivery-partner"],
  },
  {
    id: "grocery-app",
    match: ["grocery app", "supermarket delivery", "arbuz", "lavka", "quick commerce"],
    features: ["grocery-delivery", "address-autocomplete", "checkout-payment", "delivery-eta"],
  },
  {
    id: "fintech-wallet",
    match: ["fintech", "wallet app", "digital wallet", "pfm", "personal finance"],
    features: ["checkout-payment", "fx-rates", "bank-accounts", "user-auth"],
  },
  {
    id: "marketplace",
    match: ["marketplace", "multi vendor", "seller platform", "wildberries", "ozon seller"],
    features: ["marketplace-sync", "checkout-payment", "address-autocomplete", "parcel-shipping"],
  },
  {
    id: "travel-planner",
    match: ["travel app", "trip planner", "book flights", "train tickets"],
    features: ["travel-booking", "address-autocomplete", "route-planning", "map-display"],
  },
  {
    id: "ride-app",
    match: ["taxi app", "ride hail", "ride-hailing", "indriver app", "yandex go app"],
    features: ["ride-hailing", "map-display", "device-location", "route-planning", "sms-otp"],
  },
  {
    id: "gov-dashboard",
    match: ["gov dashboard", "open data portal", "statistics dashboard", "civic data", "population dashboard"],
    features: ["gov-open-data", "population-stats"],
  },
  {
    id: "health-dashboard",
    match: ["health dashboard", "hospital stats", "covid dashboard", "public health app"],
    features: ["health-stats", "gov-open-data"],
  },
  {
    id: "real-estate",
    match: ["real estate app", "property listings", "housing portal", "apartment search"],
    features: ["housing-stats", "address-autocomplete", "map-display", "forward-geocode"],
  },
  {
    id: "ai-product",
    match: ["chatbot app", "ai assistant", "voice assistant", "yandexgpt"],
    features: ["ai-assistant", "speech-ai"],
  },
  {
    id: "logistics-fleet",
    match: ["fleet management", "courier fleet", "dispatch app", "last mile logistics"],
    features: ["route-planning", "delivery-eta", "map-display", "device-location"],
  },
];

const featureById = new Map(FEATURES.map((f) => [f.id, f]));

export function getFeature(id) {
  return featureById.get(id) || null;
}

export function getParentFeature(feature) {
  if (!feature?.parentId) return null;
  return getFeature(feature.parentId);
}

export function featureSearchText(feature) {
  return [
    feature.label,
    feature.why,
    feature.where,
    ...(feature.keywords || []),
    ...(feature.capabilityTags || []),
  ]
    .filter(Boolean)
    .join(" ");
}
